Search adjustments
orwa97/Muqtatif pull request #7
Opened 2022-01-18 16:07 UTC by orwa97

معها شوية شغل المفروض تكون ع برانش جديدة بس غاب عن بالي الموضوع

2022-01-19 03:18 UTC, Hartha-aloufi requested changes

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/muqHeader/MuqHeader.jsx
> +    // });
امسح

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +  const onExport = () => {
ما في داعي لهاظ الكولباك

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/search/Search.jsx
> +      setNoOptMessage(null);
اظن ما في داعي تعمل ستيت لها وتعالج هاي الحالة هون.
شيك عليها دغري عند الريندر

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +  const [selectedVerse, setSelectedVerse] = useAtom(selectedVerseAtom);
بكفي انك تعرف رقم الآية المحددة. يعني امسح الـ isSelected

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +      // img.src = dataUrl;
امسح

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/muqHeader/MuqHeader.jsx
> +      download(img, "my-node.png");
لو تحاول تخلي اسم الصورة يكون منظم. مثلا  مقتطف مع رقم السورة والآية
"مقتطف-01-22"

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/muqHeader/MuqHeader.jsx
> +          console.log("Image Copied");
امسح

2022-01-19 03:18 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/muqHeader/MuqHeader.jsx
> +          console.log("Error: ", e.message);
امسح

2022-01-19 12:38 UTC, orwa97 commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +  const [selectedVerse, setSelectedVerse] = useAtom(selectedVerseAtom);
isSelected مستخدمها عشان اعرف انو اخذ الاية اللي جاية من السيرش بيج ولا من السيليكت اللي بالمفتطف هيدر

2022-01-24 13:39 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +      `https://api.quran.com/api/v4/quran/verses/uthmani_simple?chapter_number=${verseKey[0]}`
لا يوجد داعٍ لوضع الـ `verseKey` في useMemo
وذلك لانها كانت داخل useEffect والذي لا ينفذ مع كل تحديث

2022-01-24 13:39 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +    console.log(selectedVerseValue);
امسح

2022-01-24 13:39 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/Muqtatif.jsx
> +        console.log(selectedVerseValue);
امسح

2022-01-24 13:39 UTC, Hartha-aloufi commented on src/pages/Main/muqtatif/muqHeader/MuqHeader.jsx
> +  }, [props.verseKey]);
اكتب تعليقاً يشرح هذا

2022-01-24 13:54 UTC, merged